site_name: How to setup mkdocs
nav: 
  - Home: index.md
  - Install Python: python.md 
  - MkDocs Class: setup.md
  - Markdown Resources: markdown.md
theme: 
    name: readthedocs
    highlightjs: true
    hljs_languages: ['lua', 'javascript', 'python']
extra_css:
    - css/style.css
# extra_javascript:
#     - js/ex.js